AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 instance with Security Group"

Resources:
  LaunchWizard2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: launch-wizard-2
      GroupDescription: launch-wizard-2 created 2025-03-17T08:45:34.331Z
      VpcId: vpc-07d6cba4f67675fb4
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c2e61fdcb5495691
      InstanceType: t3.micro
      KeyName: MyEC2KeyPair
      BlockDeviceMappings:
        - DeviceName: /dev/sdb
          Ebs:
            Encrypted: false
            DeleteOnTermination: false
            Iops: 3000
            VolumeSize: 10
            VolumeType: gp3
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref LaunchWizard2SecurityGroup
      CreditSpecification:
        CPUCredits: unlimited
      Tags:
        - Key: Name
          Value: od-itstep
      PrivateDnsNameOptions:
        HostnameType: ip-name
        EnableResourceNameDnsARecord: true
        EnableResourceNameDnsAAAARecord: false
