name: Deploy to AWS

on:
  pull_request:
    paths:
      - 'Users_managed/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy creating users
        run: |
          aws cloudformation deploy \
            --stack-name DevStack \
            --template-file Users_managed/create_user_add_permission.yaml \
            --capabilities CAPABILITY_NAMED_IAM
